# Data Analytics

## Numpy

In [2]:
import numpy as np

# Python list vs NumPy array

# Python list
lst = [1, 2, 3]

# NumPy array
arr = np.array([1, 2, 3])



In [4]:
print(np.add(1,1))

2


In [5]:
# calculate the addn of 321 and 432 
print(np.add(321,432))

753


In [11]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])

a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [15]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])


(2, 3)
1 2 4


In [16]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [17]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [18]:
c = np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [19]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [28]:
e = np.random.random((2,2))
print(e)

[[0.8997679  0.83794431]
 [0.55964485 0.1449763 ]]


In [33]:
# create an array of 3x3 having all zeros
o = np.zeros((3,3))
print(o)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
# create an identity matrix of 4x4
e = np.eye(4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
# create an array of 3x2 having all numbers 5
c = np.full((3,2),7)
print(c)

[[7 7]
 [7 7]
 [7 7]]


In [36]:
# convert [10,20,30,40] into array and extract 30
b = np.array([10,20,30,40])
print(b[2])

30


In [37]:
# create an array of 3x4 with random numbers
e = np.random.random((3,4))
print(e)

[[0.7082322  0.86074444 0.59896774 0.18966548]
 [0.66034554 0.80158665 0.95394039 0.07251734]
 [0.87686227 0.71515215 0.895351   0.62280618]]


In [45]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('The number is:',a[0,3])

The number is: 4


In [49]:
a = np.array([[12,23,34,45],[56,67,78,89]])
print(a[1,1])
print(a[0,2])
print(a[1,0])
print(a[0,0])

67
34
56
12


In [60]:
b = np.array([[[2,3,4],[5,6,7],[8,9,10],[11,12,13]]])
print(b[0,2,2])
print(b[0,3,2])
print(b[0,3,1])
print(b[0,1,1])


10
13
12
6


In [61]:
c = np.array([[[[1,2],[3,4]]]])
print(c[0,0,1,0])
print(c[0,0,0,1])

3
2


In [62]:
a = np.array([[[[1,2,3],[4,5,6]]]])
print(a[0,0,1,1])

5


In [64]:
b = np.array([[[[10,20]],[[30,40]]]])  #40
print(b[0,1,0,1])

40


In [66]:
# print the square of 20 from array
b = np.array([[[[10,20]],[[30,40]]]])
print('sqr of 20:',b[0,0,0,1]*2)

sqr of 20: 40
